# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Phctl < Formula
  desc ""
  homepage "https://example.com"
  version "1.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/phoban01/myapp/releases/download/v1.2.0/phctl_Darwin_arm64.tar.gz"
      sha256 "a4b6e0d865c880e5592e4d84d60044b55c8df9397c03a2d331e22660b2f3cb34"

      def install
        bin.install "phctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/phoban01/myapp/releases/download/v1.2.0/phctl_Darwin_amd64.tar.gz"
      sha256 "33391e6d2f986400b7b9a377dd522f9629d251f2314e895fa69947696cd13fa4"

      def install
        bin.install "phctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/phoban01/myapp/releases/download/v1.2.0/phctl_Linux_armv6.tar.gz"
      sha256 "cdb99189c0d5444333650b71e97f1b93a2f5f543007e498289a9c728c759394b"

      def install
        bin.install "phctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/phoban01/myapp/releases/download/v1.2.0/phctl_Linux_arm64.tar.gz"
      sha256 "ca434633140fcd1a875a52b025f6f844a858cf931703d3781f4a038c2507ad9e"

      def install
        bin.install "phctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/phoban01/myapp/releases/download/v1.2.0/phctl_Linux_amd64.tar.gz"
      sha256 "1dace6bbd029a2534e2c243440eefd19e89e9267c804c7603097456993172623"

      def install
        bin.install "phctl"
      end
    end
  end
end
