# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Phctl < Formula
  desc ""
  homepage "https://example.com"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/phoban01/myapp/releases/download/v1.0.0/phctl_Darwin_arm64.tar.gz"
      sha256 "2620d01886f6c3e0ef7851317ef9c3eb993249edd5a242cc1b2e90bd24416182"

      def install
        bin.install "phctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/phoban01/myapp/releases/download/v1.0.0/phctl_Darwin_amd64.tar.gz"
      sha256 "1739129d3f444f78e6f9cc8f06b5db454c94331dbf83cc580df73e551351d941"

      def install
        bin.install "phctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/phoban01/myapp/releases/download/v1.0.0/phctl_Linux_armv6.tar.gz"
      sha256 "ac9bcc83ceaeead0ef555b8467ac244cd6e7b8ba03cef47ef17d7b0f1ce0b26e"

      def install
        bin.install "phctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/phoban01/myapp/releases/download/v1.0.0/phctl_Linux_arm64.tar.gz"
      sha256 "c4a83385cd2de2bf9cb3b875a45341d84aa759bc853753fd26f0bcc1e648adff"

      def install
        bin.install "phctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/phoban01/myapp/releases/download/v1.0.0/phctl_Linux_amd64.tar.gz"
      sha256 "1f2d5463222a3931dfca9cb70848ead5cf33823e5b40bb11205eadc16745d161"

      def install
        bin.install "phctl"
      end
    end
  end
end
